### PR TITLE
Location Br

### PR DESCRIPTION
**Pull request by maisonmdsgreen**

### CODE REVIEW

**Comment by danieleds** [comment]
Hi, please only use "pt" as language code.
In addition, you're missing some edits to a few more files... please ensure you've followed this guide completely: https://github.com/notepadqq/notepadqq/wiki/Translate-Notepadqq

Thanks!

**Comment by darealshinji** [comment]
I don't speak Portuguese but afaik Brazilian and European Portuguese can be different, kinda like UK and US English. Even German translations can differ (replace `ß` with `ss` and you basically have a Swiss German localization). By the way I think `pt_BR` with capital BR would be correct?

**Comment by danieleds** [comment]
Yes, right

**Comment by maisonmdsgreen** [comment]
Yes is correct Brazil is pt_br and Portugal is pt_pt

Thanks

**Comment by MurkBRA** [comment]
May I ask why it is still open? Maybe I can help...
Brazilliam portuguese is not listed on ISO 639-1
You can just set as **br**...

**Comment by SandorPetrovics** [comment]
Hi @maisonmdsgreen
Your repository is very outdated, please synchronize with https://github.com/notepadqq/notepadqq repository.
Some help for this:
https://help.github.com/articles/configuring-a-remote-for-a-fork/
https://help.github.com/articles/syncing-a-fork/
https://help.github.com/articles/pushing-to-a-remote
After it's done:
You should be update your notepadqq_pt.ts file
To update a Translation File (See: https://github.com/notepadqq/notepadqq/wiki/Translate-Notepadqq)
Run the following command:
lupdate src/ui/ui.pro -ts src/translations/notepadqq_pt.ts
translate the untranslated strings.
Then run the following command:
lupdate -no-obsolete src/ui/ui.pro -ts src/translations/notepadqq_pt.ts

**Pull request merged**
