### PR TITLE
add handel-c langage https://en.wikipedia.org/wiki/Handel-C

### PR DESCRIPTION
**Pull request by FAIG2014**
This pull request works with https://github.com/codemirror/CodeMirror/pull/4737

they are working together to add support of handel-c: https://en.wikipedia.org/wiki/Handel-C

### CODE REVIEW

**Comment by JuBan1** [comment]
Sorry it took so long to get back to this. Merged.

**Comment by danieleds** [comment]
Do this language actually work with the version of CodeMirror that we currently ship?

**Comment by JuBan1** [comment]
Derp, yea, I thought it was just using the clike mode but it's actually looking for the handel-c "submode". We could add it to our CM fork, or revert the change.

**Comment by danieleds** [comment]
Probably better if we revert for now.
We need a big change to switch to an upgraded version of CodeMirror and I'd like to do that as cleanly as possible.

**Pull request merged**
