### PR TITLE
Added regex group reuse token functionality to Replace & Replace All

### PR DESCRIPTION
**Pull request by Algomorph**
Replace & Replace All now mimics Notepad++ replace functionality
for regular expressions with groups: \[1-9] get replaced by groups
with the corresponding group in the regular expression.

**Example**

Test file contents:
hello C++ goodbye
hello JavaScript goodbye
hello CodeMirror goodbye

Regular expression in "Find" input box of the Search dialog:
```(hell)o\s*([^ ]*)\s*goodbye```

In "Replace with":
\2 is \1

Output:
C++ is hell
JavaScript is hell
CodeMirror is hell

Implements #191

### CODE REVIEW

**Comment by danieleds** [comment]
Thank you!
Two things:

**1)**
I think the example regex should be `(hell)o\s(.*)\sgoodbye`.

**2)**
I noticed a strange behavior while searching in *plain text*. Try the following steps in your original test file:
 1. Search string: `hello`
 2. Replace string: `\1 \2 \3`
 3. Click the "plain text" option
 4. Replace all

Since it is plaintext you would expect this:

    \1 \2 \3 C++ goodbye
    \1 \2 \3 JavaScript goodbye
    \1 \2 \3 CodeMirror goodbye

but you get this:

    undefined \2 \3 C++ goodbye
    undefined \2 \3 JavaScript goodbye
    undefined \2 \3 CodeMirror goodbye

Could you push a new commit to handle this case? Also, feel free to add your name to the contributors file.

For everything else it works great, thanks for the nice clean code!

**Comment by Algomorph** [comment]
@danieleds 
1) The regex I put in the pull request comment originally suffered from the markdown formatting. I've surrounded it with back-ticks. It should work as it is now. I changed the regex in the git commit message to _almost_ the same thing, with ```[^\s]``` instead of ```[^ ]```, which is the most correct. ```(.*)``` adds an extra space behind "C++" and such. For the pull request comment, I couldn't get that to work due to markdown issue...
2) This is fixed now. I also fixed a couple other things. We shouldn't get "undefined" for any case anymore. Also, if you do the "hello" search you described on the same test file, but in regex mode, the behavior of Notepad++ is different from the plain text behavior: you simply get the two spaces between the group reuse tokens ("   " instead of "\1 \2 \3"), so I made sure to handle that behavior as well.

**Comment by danieleds** [comment]
Thank you! Works great now :)

**Comment by adeel-raza-azeemi** [comment]
Notepadqq regular expression search and replace does not work properly. i.e. we can't reuse one subgroup in replace again.

**Comment by Algomorph** [comment]
@adeel-raza-azeemi , can you file a new bug, please?

**Comment by adeel-raza-azeemi** [comment]
oK i will. But just to inform you. You can test it too. replace text in a string. try to use use \1 or any other more than one time and it will only be replaced once. 

Btw: I didn't know how to file a new bug in github but i will figure it out :)

**Comment by Algomorph** [comment]
@adeel-raza-azeemi ok, thank you sir!

**Comment by adeel-raza-azeemi** [comment]
Filed the bug it #12992

**Pull request merged**
