### PR TITLE
Add "close to the left" and "close to the right" actions for editor tabs

### PR DESCRIPTION
**Pull request by ShadauxCat**
...mimicking similar functionality in notepad++.

### CODE REVIEW

**Comment by ShadauxCat** [comment]
This is one of the features of notepad++ I use most often in windows environments. After searching through countless linux editors trying to find the same functionality, I finally just gave up and decided to add it myself to notepadqq.

**Comment by danieleds** [comment]
I love this feature! It's extremely useful.

A few suggestions for the code:
 * instead of using a `closing` flag, check the index of the editor. Pseudocode of what I mean:

    ```c++
    void MainWindow::on_actionCloseRight_triggered() {
        ...
        int currEditorId = m_topEditorContainer->currentTabWidget()->currentIndex();
        m_topEditorContainer->forEachEditor([&](... editorId ...) {
            if (editorId <= currEditorId) {
                return true;
            }

            ...
        });
        ...
    }
 ```
    Same thing for CloseLeft(). This simplifies the code and should allow you to reuse it for the two menus instead of replicating it.

 * Selecting one of those options should only close the tabs in the current tab widget (not sure if this is the behavior of Notepad++, but I think it's a clearer behavior anyway). So, instead of `m_topEditorContainer->forEachEditor()`, you might want to do a for loop on `m_topEditorContainer->currentTabWidget()`.

(Regarding the second point, the "close all but this" menu is also wrong... I'll fix it asap).

Ask me anything if you need help! Looking forward for another commit :)

**Comment by ShadauxCat** [comment]
Sorry for the delay on updating this pull request. Been a busy time lately. But I wanted to drop in and say I'm going to make the requested changes and will try to get a new commit in soon.

**Comment by Teklad** [comment]
@danieleds or @Juban1 can this be closed?  Its at its 2 year anniversary so I don't see this getting updated by the original author at this point.  If one of you guys want you can make the necessary changes and push it to the repo yourself instead if the feature is still desirable.

**Comment by ShadauxCat** [comment]
@Teklad Ack! Sorry! I forgot this PR existed.... I'll try to update it soon...

**Comment by valera-rozuvan** [comment]
@Teklad Any progress?

**Comment by danieleds** [comment]
Done in ac769eaebe6b2bb083658f4c9bf964017b78074f

**Pull request closed without merging**
