### PR TITLE
Make it a hard fail if pkg-config is not installed.

### PR DESCRIPTION
**Pull request by valera-rozuvan**
On Debian, if the package `pkg-config` is not installed, `make` fails for some reason (see below for output). I propose to make the `configure` script exit if it doesn't find `pkg-config`.

```
$ make
cd src/ui/ && ( test -e Makefile || /usr/lib/x86_64-linux-gnu/qt5/bin/qmake /home/monty/dev/notepadqq/src/ui/ui.pro PREFIX=/usr/local QMAKE_CXX=c++ 'QMAKE_CXXFLAGS= ' QMAKE_LFLAGS= 'LRELEASE=/usr/bin/qtchooser -run-tool=lrelease -qt=5' CONFIG+= -o Makefile ) && make -f Makefile 
Project MESSAGE: Release build
Updating '/home/monty/dev/notepadqq/src/ui/../translations/notepadqq_de.qm'...
    Generated 453 translation(s) (453 finished and 0 unfinished)
Updating '/home/monty/dev/notepadqq/src/ui/../translations/notepadqq_es.qm'...
    Generated 454 translation(s) (454 finished and 0 unfinished)
Updating '/home/monty/dev/notepadqq/src/ui/../translations/notepadqq_fr.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/monty/dev/notepadqq/src/ui/../translations/notepadqq_hu.qm'...
    Generated 454 translation(s) (454 finished and 0 unfinished)
Updating '/home/monty/dev/notepadqq/src/ui/../translations/notepadqq_it.qm'...
    Generated 451 translation(s) (434 finished and 17 unfinished)
    Ignored 1 untranslated source text(s)
Updating '/home/monty/dev/notepadqq/src/ui/../translations/notepadqq_ja.qm'...
    Generated 447 translation(s) (447 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)
Updating '/home/monty/dev/notepadqq/src/ui/../translations/notepadqq_pl.qm'...
    Generated 452 translation(s) (452 finished and 0 unfinished)
Updating '/home/monty/dev/notepadqq/src/ui/../translations/notepadqq_pt.qm'...
    Generated 454 translation(s) (454 finished and 0 unfinished)
Updating '/home/monty/dev/notepadqq/src/ui/../translations/notepadqq_ru.qm'...
    Generated 328 translation(s) (326 finished and 2 unfinished)
    Ignored 17 untranslated source text(s)
Updating '/home/monty/dev/notepadqq/src/ui/../translations/notepadqq_sl.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/monty/dev/notepadqq/src/ui/../translations/notepadqq_sv.qm'...
    Generated 359 translation(s) (359 finished and 0 unfinished)
Updating '/home/monty/dev/notepadqq/src/ui/../translations/notepadqq_uk.qm'...
    Generated 453 translation(s) (453 finished and 0 unfinished)
Updating '/home/monty/dev/notepadqq/src/ui/../translations/notepadqq_zh.qm'...
    Generated 448 translation(s) (448 finished and 0 unfinished)
Project ERROR: uchardet development package not found
Makefile:43: recipe for target 'sub-src-ui-make_first' failed
make: *** [sub-src-ui-make_first] Error 3
```

My system:

```
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```
Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
```

### CODE REVIEW

**Comment by danieleds** [comment]
Sorry for the very late reply. Is this still relevant?
I'm somewhat hesitant to make it a hard fail, since pkg-config is not *strictly* required and in a well-prepared environment Notepadqq should be able to build regardless of its presence.

Maybe we could print a big warning in case ./configure is not able to find pkg-config?

**Comment by valera-rozuvan** [comment]
Yes. This is still an issue. Without this dep - the build process still fails:

```
$ make -j 8
cd src/ui/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/valera/dev/github.com/notepadqq/notepadqq/src/ui/ui.pro PREFIX=/usr QMAKE_CXX=c++ 'QMAKE_CXXFLAGS= ' QMAKE_LFLAGS= 'LRELEASE=/usr/bin/qtchooser -run-tool=lrelease -qt=5' CONFIG+= ) && make -f Makefile 
cd src/ui-tests/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /home/valera/dev/github.com/notepadqq/notepadqq/src/ui-tests/ui-tests.pro PREFIX=/usr QMAKE_CXX=c++ 'QMAKE_CXXFLAGS= ' QMAKE_LFLAGS= 'LRELEASE=/usr/bin/qtchooser -run-tool=lrelease -qt=5' CONFIG+= ) && make -f Makefile 
Project MESSAGE: Release build
Updating '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/../translations/notepadqq_de.qm'...
    Generated 453 translation(s) (453 finished and 0 unfinished)
Updating '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/../translations/notepadqq_es.qm'...
    Generated 454 translation(s) (454 finished and 0 unfinished)
Updating '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/../translations/notepadqq_fr.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
Updating '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/../translations/notepadqq_hu.qm'...
    Generated 454 translation(s) (454 finished and 0 unfinished)
Updating '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/../translations/notepadqq_it.qm'...
    Generated 451 translation(s) (434 finished and 17 unfinished)
    Ignored 1 untranslated source text(s)
Updating '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/../translations/notepadqq_ja.qm'...
    Generated 447 translation(s) (447 finished and 0 unfinished)
    Ignored 5 untranslated source text(s)
Updating '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/../translations/notepadqq_pl.qm'...
    Generated 452 translation(s) (452 finished and 0 unfinished)
Updating '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/../translations/notepadqq_pt.qm'...
    Generated 454 translation(s) (454 finished and 0 unfinished)
Updating '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/../translations/notepadqq_ru.qm'...
make[1]: Entering directory '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui-tests'
c++ -O2 -std=gnu++11 -Wall -W -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
    Generated 328 translation(s) (326 finished and 2 unfinished)
    Ignored 17 untranslated source text(s)
Updating '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/../translations/notepadqq_sl.qm'...
    Generated 345 translation(s) (345 finished and 0 unfinished)
/usr/lib/qt5/bin/moc -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WEBENGINEWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_TESTLIB_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/home/valera/dev/github.com/notepadqq/notepadqq/src/ui-tests"' --include /home/valera/dev/github.com/notepadqq/notepadqq/src/ui-tests/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/valera/dev/github.com/notepadqq/notepadqq/src/ui-tests -I/home/valera/dev/github.com/notepadqq/notepadqq/src/ui -I/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/libs/qtpromise/include -I/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/libs/qtpromise/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtSvg -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -I/usr/include/x86_64-linux-gnu/qt5/QtQuick -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtTest -I/usr/include/x86_64-linux-gnu/qt5/QtWebChannel -I/usr/include/x86_64-linux-gnu/qt5/QtQml -I/usr/include/x86_64-linux-gnu/qt5/QtWebSockets -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtPositioning -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/x86_64-linux-gnu/c++/8 -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-linux-gnu/8/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/8/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include tst_notepadqqtest.cpp -o tst_notepadqqtest.moc
Updating '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/../translations/notepadqq_sv.qm'...
    Generated 359 translation(s) (359 finished and 0 unfinished)
Updating '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/../translations/notepadqq_uk.qm'...
    Generated 453 translation(s) (453 finished and 0 unfinished)
Updating '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui/../translations/notepadqq_zh.qm'...
    Generated 448 translation(s) (448 finished and 0 unfinished)
Project ERROR: uchardet development package not found
make: *** [Makefile:46: sub-src-ui-make_first] Error 3
make: *** Waiting for unfinished jobs....
c++ -c -O2 -std=gnu++11 -Wall -W -D_REENTRANT -fPIC -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WEBENGINEWIDGETS_LIB -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_WEBENGINECORE_LIB -DQT_QUICK_LIB -DQT_GUI_LIB -DQT_TESTLIB_LIB -DQT_WEBCHANNEL_LIB -DQT_QML_LIB -DQT_WEBSOCKETS_LIB -DQT_NETWORK_LIB -DQT_POSITIONING_LIB -DQT_CORE_LIB -DQT_TESTCASE_BUILDDIR='"/home/valera/dev/github.com/notepadqq/notepadqq/src/ui-tests"' -I. -I../ui -I../ui/libs/qtpromise/include -I../ui/libs/qtpromise/src -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtSvg -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebEngineCore -isystem /usr/include/x86_64-linux-gnu/qt5/QtQuick -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtTest -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebChannel -isystem /usr/include/x86_64-linux-gnu/qt5/QtQml -isystem /usr/include/x86_64-linux-gnu/qt5/QtWebSockets -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtPositioning -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -I. -isystem /usr/include/libdrm -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -o tst_notepadqqtest.o tst_notepadqqtest.cpp
g++ -Wl,-O1 -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu -o ui-tests tst_notepadqqtest.o   -lQt5Svg -lQt5WebEngineWidgets -lQt5PrintSupport -lQt5Widgets -lQt5WebEngineCore -lQt5Quick -lQt5Gui -lQt5Test -lQt5WebChannel -lQt5Qml -lQt5WebSockets -lQt5Network -lQt5Positioning -lQt5Core -lGL -lpthread 
make[1]: Leaving directory '/home/valera/dev/github.com/notepadqq/notepadqq/src/ui-tests'
```

**Comment by valera-rozuvan** [comment]
On a fresh clean Debian 10 system - after I install `pkg-config` - all builds OK - and I can run `./out/release/bin/notepadqq` fine.

**Comment by danieleds** [comment]
Thank you, it's now merged :)

**Pull request merged**
