### PR TITLE
%directory% in run command.

### PR DESCRIPTION
**Pull request by qcerasmus**
fixes https://github.com/notepadqq/notepadqq/issues/433.

### CODE REVIEW

**Comment by JuBan1** [comment]
Hey,

I see a potential issue with files with a path like ".../some_file_dir/file". Since all instances of `fileName` are replaced with `""`, directories with `filename` in its name will be mangled. Also, you can get the file path without the `"file://"` by using `toLocalFile()`

Something like this should work: 

`QString directory = QFileInfo( url.toLocalFile() ).absolutePath();`

**Comment by qcerasmus** [comment]
Updated to the safer way of doing it.

**Comment by danieleds** [comment]
Thanks! There already was a pending PR (but the author didn't reply to the feedback): #398 
Can you follow those guidelines?

**Comment by qcerasmus** [comment]
I've made the changes to use the keywords that were suggested.
The translation files will need to be updated now as well.

**Pull request merged**
