### PR TITLE
Haiku got no qtchooser

### PR DESCRIPTION
**Pull request by miqlas**
Preliminary Haiku support.

### CODE REVIEW

**Comment by miqlas** [comment]
Any news here?

**Comment by miqlas** [comment]
Any news here?

**Comment by JuBan1** [comment]
Sorry about the long radio silence. I know this is a tiny patch but I want to look into the specifics before I merge it. I'll do that once I'm back home in about a week, pinky promise!

**Comment by miqlas** [comment]
@JuBan1 : okey-dokey!

**Comment by miqlas** [comment]
@danieleds : Revert? Why?

**Comment by danieleds** [comment]
@miqlas it's not reverted, for some reason that line slipped through another commit message.

**Comment by miqlas** [comment]
ok then

**Pull request merged**
