### PR TITLE
Update CodeMirror to 5.33.0

### LINKED ISSUE #511: Update to CodeMirror 5.32.0?
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/notepadqq/notepadqq/blob/master/CONTRIBUTING.md#question
```

**Current behavior**
Notepadqq builds against an ancient version of CodeMirror.

**Expected behavior**
Build against the latest version?

**Minimal reproduction of the problem with instructions**
Replaced source with CM 5.32.0, builds without issue. Seems to work without issue, too.

**Please tell us about your environment:**
Fedora 27.

### PR DESCRIPTION
**Pull request by JuBan1**
We're using CM 5.18.2 whereas 5.33.0 is the latest stable.

The [changes](https://github.com/codemirror/CodeMirror/blob/5.33.0/CHANGELOG.md) aren't overwhelming but there is a good number of bug fixes and small extra features for numerous syntax modes.
I'm currently testing Nqq with this version. If I don't find any regressions I'll pull this in a few days.

Apart from the new CM files there's only one change in `Editor.cpp` where I disable a couple of right-click menu options that have shown up after updating:

        m_webView->pageAction(QWebPage::InspectElement)->setVisible(false);
        m_webView->pageAction(QWebPage::SetTextDirectionDefault)->setVisible(false);
        m_webView->pageAction(QWebPage::SetTextDirectionLeftToRight)->setVisible(false);
        m_webView->pageAction(QWebPage::SetTextDirectionRightToLeft)->setVisible(false);

Fixes #511

### CODE REVIEW

**Comment by BearzRobotics** [comment]
I hope this lands if you need help test let me know.

**Comment by JuBan1** [comment]
If you'd like you can check this PR out and use it for a while to see if you can find any issues. I've been using it for the last two days and haven't come across anything yet though I'll give it some more time.

**Comment by danieleds** [comment]
@JuBan1 , do you have push access to our [CodeMirror fork](https://github.com/notepadqq/CodeMirror)?

Remember that we have this tricky boring step where you should first update that repo (see [instructions](https://github.com/notepadqq/notepadqq/wiki/How-to-update-CodeMirror)), and then redirect the subtree here to that version.

The reason is, we've got some modifications to the code and we need to merge those with each new update.

**Comment by JuBan1** [comment]
@danieleds I don'thave push access to that.

I think at least some of those patches are obsolete but I guess we'll want to keep the m4 mode.

**Comment by danieleds** [comment]
@JuBan1 Here it is https://github.com/notepadqq/CodeMirror/invitations

**Comment by JuBan1** [comment]
Ooookay, I believe I rebased and reapplied the patches without breaking too much, and updated the subtree. Still giving it some extra time to make sure everything works.

**Pull request merged**
