### PR TITLE
Implement --allow-root and prohibit running as root by default.

### PR DESCRIPTION
**Pull request by JuBan1**

### CODE REVIEW

**Comment by danieleds** [comment]
Before merging, I want to see if it works/compiles on macOS

**Comment by JuBan1** [comment]
Sure, give it a go.

It should work since `unistd.h` is part of POSIX which macOS also implements and a uid of 0 universally indicates root as far as I know.

**Comment by danieleds** [comment]
Perfect!

**Comment by Nadav-Eyesight** [comment]
So I just started using Notepadqq, and the one thing that bothers me is having to use `-allow-root`. Why was this added? Is there anything stopping me from simply aliasing `notepadqq --allow-root`?

**Comment by danieleds** [comment]
In a few words: because you probably don't really want to do it.

Read this discussion, which led to this change: https://github.com/notepadqq/notepadqq/issues/577

**Comment by Nadav-Eyesight** [comment]
Thanks for the quick reply. I've made a feature request.

**Pull request merged**
