### PR TITLE
Fix crash on Mac after launching #702

### PR DESCRIPTION
**Pull request by liangliangpan**
This fix has low risk, just fix the crash bug on Mac( which I have already open a bug #702).
Now it works well on Mac.
However I see some other crash related to preference dialog, which I may submit a new fix later.

### CODE REVIEW

**Comment by liangliangpan** [comment]
@danieleds could you please help to review the patch?

**Comment by liangliangpan** [comment]
@danieleds could you please help to review the patch?

**Comment by liangliangpan** [comment]
@danieleds could you please help to review the patch? The build system says it checked failed. I see the logs, the source diff in travis logs is different from what I commit. It is a little bit weird,  like something wrong in travis scripts?

**Comment by Teklad** [comment]
Looks like a formatting issue.  We check against clang-format for cpp files so we can try to keep the same formatting across all the new code (this is kinda new).

Anyways, here's the build log:
```
0.18s$ .travis/script.sh
Running clang-format against branch master, with hash 2434e38e84ff1082c9183707481dbb2f22bf0674
clang-format failed:
diff --git a/src/ui/EditorNS/editor.cpp b/src/ui/EditorNS/editor.cpp
index b84af80..78c2f0a 100644
--- a/src/ui/EditorNS/editor.cpp
+++ b/src/ui/EditorNS/editor.cpp
@@ -239,7 +239,7 @@ namespace EditorNS
     bool Editor::isClean()
     {
         QVariant data(0);
-        return asyncSendMessageWithResult("C_FUN_IS_CLEAN",data).get().toBool();
+        return asyncSendMessageWithResult("C_FUN_IS_CLEAN", data).get().toBool();
     }
```

Looks like your spacing is just a bit off.  If you can correct that, it should allow the build to pass.

**Comment by danieleds** [comment]
Thanks. Could you also add a comment specifying that this fixes a crash on macOS? So that we aren't tempted to refactor it in the future.

**Comment by JuBan1** [comment]
Looking at this, it's probably not just a fix for macOS. We pass a temporary into the `asyncSendMessageWithResult` function call that takes its argument as a references (and internally passes it along). Somewhere along that path it probably keeps a reference to that QVariant that lives past the end of the async call. That's undefined behavior.

**Comment by danieleds** [comment]
@JuBan1 nice catch. We'd have to see if we do the same for other calls.

**Pull request merged**
