### PR TITLE
Refactored DocEngine::loadDocuments.

### PR DESCRIPTION
**Pull request by JuBan1**
Here's what's done:

* Removed all the different loading functions from DocEngine (`loadDocument`, `loadDocuments`, `loadDocumentSilent`, `reloadDocument`, etc)
* Added a single new `loadDocuments(DocEngine::DocumentLoader&)` function.
* `DocumentLoader` is a simple wrapper class that contains all the possible arguments important for loading documents. This makes it much clearer what function invokation does what sort of work.

I was inspired to do this refactoring when I had to add yet another parameter to `loadDocuments` to handle:

* ~~Adding option to warn about loading large text files. (Can be set in Preferences)~~

An example of what this means for document loading. Instead of:

    m_docEngine->reloadDocument(tabWidget, tab, codec, bom); // What does this even do?!

It's now:

    m_docEngine->getDocumentLoader()
            .setUrl(editor->filePath())
            .setTabWidget(tabWidget)
            .setTextCodec(codec) // All those are optional
            .setBOM(bom)
            .setIsReload(true)
            .execute(); // Run the operation with the given params

I think this is a change for the better, especially if `loadDocuments` becomes even more complex in the future. But since it's a pretty significant change and might also affect the WebEngine branch I want to get your okay first, @danieleds.

### CODE REVIEW

**Comment by danieleds** [comment]
So nice!
I'd like to test it also on the webengine branch but could you first split the PR in more self-contained parts? I see there are changes about preferences that don't seem to belong here

**Comment by JuBan1** [comment]
Yea, this shouldn't really have been there. 

The DocEngine refac is now self-contained in this PR. I'll submit the other PR once this is in.

**Comment by danieleds** [comment]
There seem to be a conflict due to the new command line options.

Anyway, the conflicts with the WebEngine branch should be minimal and not really a problem.

Before merging, as this is a pretty delicate change, I want to be sure there are no bugs, and in particular I'd like to test every function that this change affects (reloading from the menu, reloading from the banner, etc). The old code was pretty messy.

**Comment by JuBan1** [comment]
Resolved.

I tested the affected functionality on my side and didn't notice any issues. The changes done to the load function itself are mostly cosmetic to tidy things up a bit.

**Pull request merged**
