### PR TITLE
Revert "Making use of GitHub Markdown Task Lists"

### PR DESCRIPTION
**Pull request by danieleds**
Reverts notepadqq/notepadqq#503

### CODE REVIEW

**Comment by JayTurnr** [comment]
Was there something wrong with it?

**Comment by danieleds** [comment]
I found out that github UI was implying something like "1/3 cheched => 33% completed".
Not quite our case :)

**Comment by JayTurnr** [comment]
Oh, oops! My bad! Strange it says it reverts #504 yet it doesn't.

**Comment by danieleds** [comment]
Yep, I don't know what happened

**Pull request merged**
