### PR TITLE
Update notepadqq_it.ts

### PR DESCRIPTION
**Pull request by Mek101**
Updated italian translation

### CODE REVIEW

**Comment by JuBan1** [comment]
Thanks! Merged.

**Comment by Mek101** [comment]
@JuBan1 Sorry, I know it's the wrong place, but may I ask you how to implement characters like "ù", "à" and similar in the translation files? Or perhaps, what's the name of the format their written?

Thanks

**Comment by JuBan1** [comment]
@Mek101 The translations files should be able to contain them from the get-to. Or do you mean how to type them? I'm not sure if it's standard but typing ` followed by an e,i,o,u,a produces the è, ì, etc for me.

**Comment by Mek101** [comment]
I mean how to type those characters between the `<translation>` tags. I saw that `'` it's instead typed as `&apos;` 

ex:
`don&apos;t` instead of `don't`

**Comment by JuBan1** [comment]
You should be able to just type them normally. `'` is one of the characters that gets escaped because they could interfere with how the translation file is read.

Looking at [other translation files](https://github.com/notepadqq/notepadqq/blob/master/src/translations/notepadqq_pt.ts) they just contain accented letters in text, without anything special.

**Pull request merged**
