### PR TITLE
README: Notepadqq is now available in Solus

### PR DESCRIPTION
**Pull request by joebonrichie**
Hey, i'll be the new maintainer for `notepadqq` in Solus. Notepadqq is currently in the unstable repo and will be promoted to the stable repo this Friday (10/03), you might want to only merge this then to avoid any confusion.

You can find the build recipe [here](https://dev.solus-project.com/source/notepadqq/browse/master/package.yml)

I also noticed you guys don't provide any appstream data. If you guys could provide that in the future so notepadqq integrates nicely into our Software Centre that would be appreciated (I can create a separate issue for this)

### CODE REVIEW

**Comment by danieleds** [comment]
Thanks!

>  If you guys could provide that in the future so notepadqq integrates nicely into our Software Centre that would be appreciated (I can create a separate issue for this)

Sure, a separate issue would be helpful

**Comment by danieleds** [comment]
(messed up... too used at merging)

**Comment by joebonrichie** [comment]
It's now in the stable repo in Solus, you can re-merge this

**Comment by danieleds** [comment]
Done, thanks

**Pull request merged**
