### PR TITLE
[Test] Test of bad formatting

### PR DESCRIPTION
**Pull request by danieleds**

### CODE REVIEW

**Comment by danieleds** [comment]
@Teklad there doesn't seem to be any indication about the failed formatting.

screen shot 2018-05-13 at 12 32 28

I'm trying to migrate from travis-ci.org to travis-ci.com, this *should* allow to solve this by using the new Checks API.

**Comment by Teklad** [comment]
That's because the "build" will pass still.  Travis doesn't have a way to show allowed_failures (yet).  We can just modify it to make the entire build fail for now... but if you go to Travis it'll show you that the formatting test failed.

```bash
Running clang-format against branch master, with hash 58a7e0b296955baf246840752e8f63f2ae5193a8
clang-format failed:
diff --git a/src/ui/notepadqq.cpp b/src/ui/notepadqq.cpp
index 261d55f..2319b2d 100644
--- a/src/ui/notepadqq.cpp
+++ b/src/ui/notepadqq.cpp
@@ -16,11 +16,10 @@ QString Notepadqq::copyright()
     return QObject::trUtf8("Copyright © 2010-%1, Daniele Di Sarli").arg(COPYRIGHT_YEAR);
 }
 
-QString Notepadqq::appDataPath (QString fileName)
+QString Notepadqq::appDataPath(QString fileName)
 {
 #ifdef Q_OS_MACX
-      QString def = QString("%1/../Resources/").
-            arg(qApp->applicationDirPath());
+    QString def = QString("%1/../Resources/").arg(qApp->applicationDirPath());
 #else
     QString def = QString("%1/../appdata/").
             arg(qApp->applicationDirPath());
@@ -31,11 +30,11 @@ QString Notepadqq::appDataPath (QString fileName)
                 arg(qApp->applicationDirPath()).
                 arg(qApp->applicationName().toLower());
 
-    if(!fileName.isNull()) {
+    if (!fileName.isNull()) {
         def.append(fileName);
     }
 
-       return def;
+    return def;
 }
 
 QString Notepadqq::editorPath()
```

**Comment by Teklad** [comment]
This actually shows up in Travis CI with as a failure for that step in the process.  It's unfortunate that Travis doesn't have a "Warning" style system as well.

**Comment by danieleds** [comment]
Yup, the fact is, I was hoping to see it directly from GitHub.
Anyway I think it will be automatically fixed as soon as our project moves to travis-ci.com

**Comment by Teklad** [comment]
Actually that's what I was banking on, lol.  I saw the blog post about it just a day or two ago.  I'm hopeful the tighter integration will smooth it out how I'd like.

**Pull request closed without merging**
