### PR TITLE
chore:  Remove LRELEASE configuration option in favor of built-in function.

### PR DESCRIPTION
**Pull request by JuBan1**
We did the work in `configure` but not in QMake yet. With this, one can finally build entirely without qtchooser.

### CODE REVIEW

**Comment by JuBan1** [comment]
Updated. This is certainly a lot cleaner. Especially without LRELEASE in ./configure either. 

Though, we've now lost the ability to set it manually. It was introduced because of #206 but this shouldn't be a problem when QMake provides lrelease on its own. If you're still interested in Nqq, @darealshinji, perhaps you could give it a try?

**Comment by Teklad** [comment]
Well you could still provide the --lrelease flag as an override and check if it's set before running qtPrepareTool.

**Comment by JuBan1** [comment]
Could, yes. But I'd rather get rid of it entirely if there's no need anymore.

**Comment by Teklad** [comment]
Agreed.  Now just need a couple of people to test to make sure it works across the board, lol.

**Pull request closed without merging**
