### PR TITLE
new icon theme (work in progress)

### PR DESCRIPTION
**Pull request by danieleds**
I'm adding a few Google icons.

- [x] still need to add a few missing icons
- [x] still need to add light icons
  - [x] turns out, the color isn't specified anywhere within the svg. In fact, on the website, the downloaded file is the same for both light and dark icons. Maybe we're able to assign a color from within c++.
- [x] License statements:
    - https://github.com/KDE/breeze-icons
    - https://material.io/resources/icons/
- [x] Light theme: better mousedown feedback

### CODE REVIEW

**Comment by danieleds** [comment]
Probably useful:

https://stackoverflow.com/questions/43125339/creating-qicon-from-svg-contents-in-memory

**Comment by Teklad** [comment]
This will fix both #768 and #659 yes?

**Comment by danieleds** [comment]
> This will fix both #768 and #659 yes?

yep

**Comment by JuBan1** [comment]
I found this as a possible solution: https://www.qtcentre.org/threads/53946-Is-it-possible-to-change-color-of-a-QGraphicsSvgItem

Don't know much about how SVG items work but that seems like an option.

**Comment by Teklad** [comment]
Yea it would make a lot more sense just to invert the color since we're strictly targeting light/dark.

**Comment by danieleds** [comment]
Yes, that's my plan. It can be done but it won't be pretty, I guess.

**Comment by Teklad** [comment]
Couldn't you convert the QIcon to a QPixmap and adjust the color map?  I'm pretty sure that would work if you index the image.  I couldn't say for sure though.

**Comment by Teklad** [comment]
Have a look at: http://doc.qt.io/qt-5/qpixmap.html#createMaskFromColor

Using a mask might be a little easier than fiddling with the color map.

**Comment by danieleds** [comment]
The thing is, these icons are basically small text strings like this one:

    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
        <path d="M0 0h24v24H0z" fill="none"/>
        <path d="M18.4 10.6C16.55 8.99 14.15 8 11.5 8c-4.65 0-8.58 3.03-9.96 7.22L3.9 16c1.05-3.19 4.05-5.5 7.6-5.5 1.95 0 3.73.72 5.12 1.88L13 16h9V7l-3.6 3.6z"/>
    </svg>

we'd just need to stick a "stroke=color" in the right place. But without a costly parser, we'd need to use some sort of hacky template.

**Comment by danieleds** [comment]
@JuBan1 yes, any other option seems too complicated.

I just need to find some of the missing icons and we're basically done.

**Comment by scx** [comment]
I'm sure you are aware of the missing icons problem.

```
Missing icon:  "edit-clear"
Missing icon:  "go-previous"
Missing icon:  "go-next"
Missing icon:  "go-bottom"
Missing icon:  "view-refresh"
Missing icon:  "document-open-recent"
Missing icon:  "application-exit"
Missing icon:  "edit-delete"
Missing icon:  "edit-select-all"
Missing icon:  "go-next"
Missing icon:  "go-previous"
Missing icon:  "go-jump"
Missing icon:  "view-fullscreen"
Missing icon:  "system-run"
Missing icon:  "window-new"
Missing icon:  "help-about"
```

Here you will find out about a similar problem with the proposed solution:
https://github.com/manisandro/gImageReader/issues/73#issuecomment-453829372

**Comment by danieleds** [comment]
It also works nice by default with realtime theme changes on MacOS:

nqqtheming

**Comment by danieleds** [comment]
#659 is fixed

**Pull request merged**
