### PR TITLE
Create notepadqq_sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Hi,

Here's a Swedish translation for this great application. Coming from Windows environment and Notepad++, finding this application really made my day. :+1: 

I found some buttons that don't translate...

screen_2016-11-10_19 48 01
screen_2016-11-10_21 21 38

### CODE REVIEW

**Comment by danieleds** [comment]
Thanks!
I tried your commit and those buttons get correctly translated for me...

Can you try following the updated steps in the wiki? https://github.com/notepadqq/notepadqq/wiki/Translate-Notepadqq

You can add another commit to this PR. And then we can merge :)

**Comment by eson57** [comment]
Ok, then I don't know what is wrong on my side. I installed notepadqq from your ppa on my machine.

**Comment by danieleds** [comment]
Exactly. Anyway, the translation file looks fine... Merging!

**Comment by eson57** [comment]
Thanks! Button translation works fine with source compile.

**Pull request closed without merging**
