### PR TITLE
Revert "Vector icon: translate text to path"

### PR DESCRIPTION
**Pull request by danieleds**
Reverts notepadqq/notepadqq#474

The font is different in the "path" version.

Here you can see the PNG version (left) compared to the old SVG (right):

nqq_orig

And here is the same PNG version (left) compared to the new SVG (right):

nqq_new

In addition, the SVGs in `support_files/icons/hicolor/scalable/apps` and `src/ui/icons/notepadqq/scalable` weren't updated. 
If I remember correctly, their hash is somewhat different from that of images/notepadqq.svg because images/notepadqq.svg is an "inkscape svg" and the others are "pure svg" or something like that.

@JuBan1 @darealshinji

### CODE REVIEW

**Comment by darealshinji** [comment]
Did you compare them in Inkscape?
This is what the current icon looks like rendered by Github:
icon

I was using this tutorial: https://www.youtube.com/watch?v=_01Jdvr7eXI

**Comment by danieleds** [comment]
I compared them with a desktop application, and on GitHub I was seeing them exactly like in the desktop application.

I suspect your're missing some font on your system, that's why it falls back to that similar but different font.

I compared with the PNG to make sure that *I* wasn't missing any font ;)

**Comment by danieleds** [comment]
P.S. A path conversion would be great exactly for this reason. We just need the right font.

**Comment by danieleds** [comment]
By the way, it's probably Verdana

**Comment by JuBan1** [comment]
You're right- the PNG looks different. The two SVGs are the same on my system as well which is what I compared to look for differences.

**Comment by darealshinji** [comment]
The left font seems to be Verdana. The right one isn't. @danieleds can you try to figure out which font it is? Or, if the font is displayed the intended way on your computer, can you do the path conversion yourself?

30027427-3fe48f78-9181-11e7-984b-5152117ce296

**Comment by danieleds** [comment]
The left one is how it is supposed to look: the font is Verdana.

I'll do the conversion myself later in the day 👍

**Comment by darealshinji** [comment]
Here's a changed SVG using Verdana:
[notepadqq.svg](https://github.com/notepadqq/notepadqq/files/1277615/notepadqq.svg.txt)
[notepadqq.svg.diff](https://github.com/notepadqq/notepadqq/files/1277614/notepadqq.svg.diff.txt)

**Comment by danieleds** [comment]
@darealshinji how did you manage, in the old PR, to preserve the original text together the path?

**Comment by danieleds** [comment]
oh ok, you just moved it, nevermind

**Pull request merged**
